### PR TITLE
Logos

### PR DESCRIPTION
**Pull request by marcDeSantis**
OK - what did I do wrong here?

### CODE REVIEW

**Comment by marcDeSantis** [comment]
Here is my merge conflict. Should I not have ran gulp??

```
<<<<<<< HEAD
  <script src="scripts/app-86a5553f82.js"></script>
=======
  <script src="scripts/app-416d239e7f.js"></script>
>>>>>>> origin/master
```

**Comment by stlcubsfan** [comment]
Did you run gulp or gulp build?

**Comment by marcDeSantis** [comment]
Just gulp

**Comment by stlcubsfan** [comment]
try running gulp again...it should blow away your dist directory and recreate it

**Comment by marcDeSantis** [comment]
OK - that did it.

**Comment by cvharris** [comment]
Marc I think there may be some small snags with img size in that tiny space but nothing a lil CSS couldn’t fix. You can merge this and I’ll take a look at it when I do polishing

**Pull request merged**
